{
    "openapi": "3.0.2",
    "info": {
        "title": "RCPCH Digital Growth API",
        "description": "Returns SDS and centiles for child growth measurements using growth references. Currently provides calculations based on the UK-WHO, Turner's Syndrome and Trisomy-21 references.",
        "version": "3.1.0"
    },
    "paths": {
        "/uk-who/calculation": {
            "post": {
                "tags": [
                    "uk-who"
                ],
                "summary": "Uk Who Calculation",
                "description": "## UK-WHO Centile and SDS Calculations\n    \n* These are the 'standard' centiles for children in the UK. It uses a hybrid of the WHO and UK90 datasets.  \n* For non-UK use you may need the WHO-only or CDC charts which we do not yet support, but we may add if demand is there.  Please contact us.\n* Returns a single centile/SDS calculation for the selected `measurement_method`.  \n* Gestational age correction will be applied automatically if appropriate according to the gestational age at birth data supplied.  \n* Available `measurement_method`s are: `height`, `weight`, `bmi`, or `ofc` (OFC = occipitofrontal circumference = 'head circumference').  \n* Note that BMI must be precalculated for the `bmi` function.  \n* Dates will discard anything after first 'T' in `YYYY-MM-DDTHH:MM:SS.milliseconds+TZ` etc",
                "operationId": "uk_who_calculation_uk_who_calculation_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/MeasurementRequest"
                            },
                            "example": {
                                "birth_date": "2020-04-12",
                                "observation_date": "2020-06-12",
                                "observation_value": 60,
                                "measurement_method": "height",
                                "sex": "male",
                                "gestation_weeks": 40,
                                "gestation_days": 4
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/uk-who/chart-coordinates": {
            "post": {
                "tags": [
                    "uk-who"
                ],
                "summary": "Uk Who Chart Coordinates",
                "description": "## UK-WHO Chart Coordinates data.\n    \n* Returns coordinates for constructing the lines of a traditional growth chart, in JSON format\n",
                "operationId": "uk_who_chart_coordinates_uk_who_chart_coordinates_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ChartCoordinateRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/uk-who/fictional-child-data": {
            "post": {
                "tags": [
                    "uk-who"
                ],
                "summary": "Fictional Child Data",
                "description": "## UK-WHO Fictional Child Data Endpoint\n\n* Generates synthetic data for demonstration or testing purposes",
                "operationId": "fictional_child_data_uk_who_fictional_child_data_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/FictionalChildRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/turner/calculation": {
            "post": {
                "tags": [
                    "turners-syndrome"
                ],
                "summary": "Turner Calculation",
                "description": "## Turner's Syndrome Centile and SDS Calculations.\n    \n* This endpoint MUST ONLY be used for **female** children with the chromosomal disorder Turner's Syndrome (45,XO karyotype).  \n* Returns a single centile/SDS calculation for the selected `measurement_method`.  \n* Gestational age correction will be applied automatically if appropriate, according to the gestational age at birth data supplied.  \n* Available `measurement_method`s are: `height` **only** because this reference data is all that exists.  \n* Dates will discard anything after first 'T' in YYYY-MM-DDTHH:MM:SS.milliseconds+TZ etc",
                "operationId": "turner_calculation_turner_calculation_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/MeasurementRequest"
                            },
                            "example": {
                                "birth_date": "2020-04-12",
                                "observation_date": "2024-06-12",
                                "observation_value": 78,
                                "measurement_method": "height",
                                "sex": "female",
                                "gestation_weeks": 39,
                                "gestation_days": 2
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/turner/chart-coordinates": {
            "post": {
                "tags": [
                    "turners-syndrome"
                ],
                "summary": "Turner Chart Coordinates",
                "description": "## Turner's Syndrome Chart Coordinates data.\n\n* Returns coordinates for constructing the lines of a traditional growth chart, in JSON format\n* Note height in girls conly be only returned. It is a post request to maintain consistency with other routes.\n",
                "operationId": "turner_chart_coordinates_turner_chart_coordinates_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ChartCoordinateRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/turner/fictional-child-data": {
            "post": {
                "tags": [
                    "turners-syndrome"
                ],
                "summary": "Fictional Child Data",
                "description": "## Turner's Fictional Child Data Endpoint\n\n* Generates synthetic data for demonstration or testing purposes",
                "operationId": "fictional_child_data_turner_fictional_child_data_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/FictionalChildRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/trisomy-21/calculation": {
            "post": {
                "tags": [
                    "trisomy-21"
                ],
                "summary": "Trisomy 21 Calculation",
                "description": "# Trisomy-21 Centile and SDS Calculations.\n\n* This endpoint MUST ONLY be used for children with Trisomy 21 (Down's Syndrome).  \n* Returns a single centile/SDS calculation for the selected `measurement_method`.  \n* Gestational age correction will be applied automatically if appropriate according to the gestational age at birth data supplied.  \n* Available `measurement_method`s are: `height`, `weight`, `bmi`, or `ofc` (OFC = occipitofrontal circumference = 'head circumference').  \n* Note that BMI must be precalculated for the `bmi` function.  ",
                "operationId": "trisomy_21_calculation_trisomy_21_calculation_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/MeasurementRequest"
                            },
                            "example": {
                                "birth_date": "2020-04-12",
                                "observation_date": "2020-06-12",
                                "observation_value": 60,
                                "measurement_method": "height",
                                "sex": "male",
                                "gestation_weeks": 40,
                                "gestation_days": 4
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/trisomy-21/chart-coordinates": {
            "post": {
                "tags": [
                    "trisomy-21"
                ],
                "summary": "Trisomy 21 Chart Coordinates",
                "description": "## Trisomy-21 Chart Coordinates Data.\n    \n* Returns coordinates for constructing the lines of a traditional growth chart, in JSON format\n* Requires a sex ('male' or 'female' lowercase) and a measurement_method ('height', 'weight' ,'bmi', 'ofc')\n",
                "operationId": "trisomy_21_chart_coordinates_trisomy_21_chart_coordinates_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ChartCoordinateRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/trisomy-21/fictional-child-data": {
            "post": {
                "tags": [
                    "trisomy-21"
                ],
                "summary": "Fictional Child Data",
                "description": "## Trisomy-21 Fictional Child Data Endpoint\n\n* Generates synthetic data for demonstration or testing purposes",
                "operationId": "fictional_child_data_trisomy_21_fictional_child_data_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/FictionalChildRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/": {
            "get": {
                "tags": [
                    "openapi3"
                ],
                "summary": "Root",
                "description": "# API spec endpoint\n* The root `/` API endpoint returns the openAPI3 specification in JSON format\n* This spec is also available in the root of the server code repository",
                "operationId": "root__get",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "ChartCoordinateRequest": {
                "title": "ChartCoordinateRequest",
                "required": [
                    "sex",
                    "measurement_method"
                ],
                "type": "object",
                "properties": {
                    "sex": {
                        "title": "Sex",
                        "enum": [
                            "male",
                            "female"
                        ],
                        "type": "string"
                    },
                    "measurement_method": {
                        "title": "Measurement Method",
                        "enum": [
                            "height",
                            "weight",
                            "ofc",
                            "bmi"
                        ],
                        "type": "string"
                    }
                }
            },
            "FictionalChildRequest": {
                "title": "FictionalChildRequest",
                "required": [
                    "measurement_method",
                    "sex",
                    "reference"
                ],
                "type": "object",
                "properties": {
                    "measurement_method": {
                        "title": "Measurement Method",
                        "enum": [
                            "height",
                            "weight",
                            "ofc",
                            "bmi"
                        ],
                        "type": "string"
                    },
                    "sex": {
                        "title": "Sex",
                        "enum": [
                            "male",
                            "female"
                        ],
                        "type": "string"
                    },
                    "start_chronological_age": {
                        "title": "Start Chronological Age",
                        "type": "number",
                        "default": 0.0
                    },
                    "end_age": {
                        "title": "End Age",
                        "type": "number",
                        "default": 20.0
                    },
                    "gestation_weeks": {
                        "title": "Gestation Weeks",
                        "type": "integer",
                        "default": 40
                    },
                    "gestation_days": {
                        "title": "Gestation Days",
                        "type": "integer",
                        "default": 0
                    },
                    "measurement_interval_type": {
                        "title": "Measurement Interval Type",
                        "enum": [
                            "d",
                            "day",
                            "days",
                            "w",
                            "week",
                            "weeks",
                            "m",
                            "month",
                            "months",
                            "y",
                            "year",
                            "years"
                        ],
                        "type": "string",
                        "default": "days"
                    },
                    "measurement_interval_number": {
                        "title": "Measurement Interval Number",
                        "type": "integer",
                        "default": 20
                    },
                    "start_sds": {
                        "title": "Start Sds",
                        "type": "number",
                        "default": 0
                    },
                    "drift": {
                        "title": "Drift",
                        "type": "boolean",
                        "default": false
                    },
                    "drift_range": {
                        "title": "Drift Range",
                        "type": "number",
                        "default": -0.05
                    },
                    "noise": {
                        "title": "Noise",
                        "type": "boolean",
                        "default": false
                    },
                    "noise_range": {
                        "title": "Noise Range",
                        "type": "number",
                        "default": 0.005
                    },
                    "reference": {
                        "title": "Reference",
                        "enum": [
                            "uk-who",
                            "trisomy-21",
                            "turners-syndrome"
                        ],
                        "type": "string"
                    }
                }
            },
            "HTTPValidationError": {
                "title": "HTTPValidationError",
                "type": "object",
                "properties": {
                    "detail": {
                        "title": "Detail",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/ValidationError"
                        }
                    }
                }
            },
            "MeasurementRequest": {
                "title": "MeasurementRequest",
                "required": [
                    "birth_date",
                    "measurement_method",
                    "observation_date",
                    "observation_value",
                    "sex"
                ],
                "type": "object",
                "properties": {
                    "birth_date": {
                        "title": "Birth Date",
                        "type": "string",
                        "description": "Date of birth of the patient, in the format YYYY-MM-DD",
                        "format": "date"
                    },
                    "gestation_days": {
                        "title": "Gestation Days",
                        "maximum": 6.0,
                        "minimum": 0.0,
                        "type": "integer",
                        "description": "The number of additional days _beyond the completed weeks of gestation_ at which the patient was born, passed as an integer. Supplying this data enables Gestational Age correction if the child was not born at term. If no gestational age is passed then term is assumed. IMPORTANT: See also the other parameter `gestation_weeks` - both are usually required.",
                        "default": 0
                    },
                    "gestation_weeks": {
                        "title": "Gestation Weeks",
                        "maximum": 44.0,
                        "minimum": 22.0,
                        "type": "integer",
                        "description": "The number of completed weeks of gestation at which the patient was born, passed as an integer. Supplying this data enables Gestational Age correction if the child was not born at term. If no gestational age is passed then 40 weeks (term) is assumed. **IMPORTANT: See also the other parameter `gestation_days` - both are usually required.**",
                        "default": 40
                    },
                    "measurement_method": {
                        "title": "Measurement Method",
                        "enum": [
                            "height",
                            "weight",
                            "ofc",
                            "bmi"
                        ],
                        "type": "string",
                        "description": "The type of measurement performed on the infant or child as a string which can be `height`, `weight`, `bmi` or `ofc`. The value of this measurement is supplied as the `observation_value` parameter. The measurements represent height **in centimetres**, weight *in kilograms**, body mass index **in kilograms/metre\u00b2** and occipitofrontal circumference (head circumference, OFC) **in centimetres**."
                    },
                    "observation_date": {
                        "title": "Observation Date",
                        "type": "string",
                        "description": "Date of the observation, in the format YYYY-MM-DD.",
                        "format": "date"
                    },
                    "observation_value": {
                        "title": "Observation Value",
                        "type": "number",
                        "description": "The value of the measurement supplied. This is supplied as a floating point number. All measurements should be supplied as **centimetres**, with the exception of Body Mass Index which is supplied as kilograms per metre squared (kg/m\u00b2)."
                    },
                    "sex": {
                        "title": "Sex",
                        "enum": [
                            "male",
                            "female"
                        ],
                        "type": "string",
                        "description": "The sex of the patient, as a string value which can either be `male` or `female`. Abbreviations or alternatives are not accepted."
                    }
                },
                "description": "This class definition creates a Python model which can be converted by FastAPI to openAPI3 schema.\nWe aim to specify all textual information, constraints, and validation here.\nIt all ends up in the openAPI documentation, automagically."
            },
            "ValidationError": {
                "title": "ValidationError",
                "required": [
                    "loc",
                    "msg",
                    "type"
                ],
                "type": "object",
                "properties": {
                    "loc": {
                        "title": "Location",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "msg": {
                        "title": "Message",
                        "type": "string"
                    },
                    "type": {
                        "title": "Error Type",
                        "type": "string"
                    }
                }
            }
        }
    }
}